table dim_year
	lineageTag: 3b6f8b97-5e8a-547a-8c2c-0662c0a24a56

	column year
		dataType: int64
		lineageTag: a48b82f3-41c2-5891-bb73-49293223121e
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column sod_as_of_date
		dataType: string
		lineageTag: ed2cbd04-84ee-5233-852d-1841da3f6b50
		summarizeBy: none
		sourceColumn: sod_as_of_date

		annotation SummarizationSetBy = Automatic

	partition dim_year = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataFolder & "\dim_year.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"year", Int64.Type}, {"sod_as_of_date", type text}})
			in
			    Typed

	annotation PBI_ResultType = Table
