table dim_branch
	lineageTag: 62c95e1f-de0e-5fa3-979f-67a37dbb02a9

	column uninumbr
		dataType: string
		lineageTag: a77c1bd8-596d-5519-b4f2-5c057a07771f
		summarizeBy: none
		sourceColumn: uninumbr

		annotation SummarizationSetBy = Automatic

	column cert
		dataType: string
		lineageTag: 0e27775b-1644-5ad9-be39-f6968c22b876
		summarizeBy: none
		sourceColumn: cert

		annotation SummarizationSetBy = Automatic

	column institution_name
		dataType: string
		lineageTag: 4a5237a1-9610-5120-8939-f0f50a79e6e2
		summarizeBy: none
		sourceColumn: institution_name

		annotation SummarizationSetBy = Automatic

	column address
		dataType: string
		lineageTag: fb83927d-a036-5c08-a0e4-0352be15b663
		summarizeBy: none
		sourceColumn: address

		annotation SummarizationSetBy = Automatic

	column city
		dataType: string
		lineageTag: a7abb7b8-baec-5989-ba2a-3a833c05cf79
		summarizeBy: none
		sourceColumn: city

		annotation SummarizationSetBy = Automatic

	column state
		dataType: string
		lineageTag: 77594619-4f47-580e-b437-67387ecfa084
		summarizeBy: none
		sourceColumn: state

		annotation SummarizationSetBy = Automatic

	column county_fips
		dataType: string
		lineageTag: adb945c4-6fde-5bab-a706-08ff4d5f65ef
		summarizeBy: none
		sourceColumn: county_fips

		annotation SummarizationSetBy = Automatic

	column latitude
		dataType: double
		lineageTag: fc98a3f4-0b19-578a-91f1-1b1b308167ea
		summarizeBy: none
		sourceColumn: latitude

		annotation SummarizationSetBy = Automatic

	column longitude
		dataType: double
		lineageTag: 309ef5fd-b4fc-5669-8e5b-3365bf836d1d
		summarizeBy: none
		sourceColumn: longitude

		annotation SummarizationSetBy = Automatic

	column tract_geoid
		dataType: string
		lineageTag: 8440c799-7ed3-53e8-aff8-3f7a4589bdab
		summarizeBy: none
		sourceColumn: tract_geoid

		annotation SummarizationSetBy = Automatic

	column service_type
		dataType: string
		lineageTag: 6d413cbd-0398-5f95-9185-54dfc6ae3c17
		summarizeBy: none
		sourceColumn: service_type

		annotation SummarizationSetBy = Automatic

	column is_main_office
		dataType: string
		lineageTag: db3dd8fb-5a65-5ca3-963c-c6c92f8cb9ed
		summarizeBy: none
		sourceColumn: is_main_office

		annotation SummarizationSetBy = Automatic

	column first_year
		dataType: int64
		lineageTag: a934a051-4ac6-5f0d-8508-4dad141deddf
		summarizeBy: none
		sourceColumn: first_year

		annotation SummarizationSetBy = Automatic

	column last_year
		dataType: int64
		lineageTag: 8fcb9416-29fa-52d2-a0ce-ce1884cda0a2
		summarizeBy: none
		sourceColumn: last_year

		annotation SummarizationSetBy = Automatic

	column drift_kind
		dataType: string
		lineageTag: 6c39aa89-caff-545a-9915-9486e2b23aff
		summarizeBy: none
		sourceColumn: drift_kind

		annotation SummarizationSetBy = Automatic

	column position_drift_miles
		dataType: double
		lineageTag: 6062a26e-7f28-52e3-a51d-402262f2ddc2
		summarizeBy: none
		sourceColumn: position_drift_miles

		annotation SummarizationSetBy = Automatic

	column county_agrees
		dataType: boolean
		lineageTag: e2461fec-6dd3-54ff-98b1-9079d9270fe2
		summarizeBy: none
		sourceColumn: county_agrees

		annotation SummarizationSetBy = Automatic

	column validity
		dataType: string
		lineageTag: 0c89b412-7404-52ea-b400-b79734a787c2
		summarizeBy: none
		sourceColumn: validity

		annotation SummarizationSetBy = Automatic

	column is_subject_bank
		dataType: boolean
		lineageTag: 84ecfbb2-41b0-5390-83c3-14c81fab87d2
		summarizeBy: none
		sourceColumn: is_subject_bank

		annotation SummarizationSetBy = Automatic

	column index_size_adjusted
		dataType: double
		lineageTag: fb8baa63-2661-5404-8038-8e7181b6d550
		summarizeBy: none
		sourceColumn: index_size_adjusted

		annotation SummarizationSetBy = Automatic

	column index_raw
		dataType: double
		lineageTag: 4114b025-ebd9-5cc7-bef7-c8284974c46f
		summarizeBy: none
		sourceColumn: index_raw

		annotation SummarizationSetBy = Automatic

	column diagnosis
		dataType: string
		lineageTag: 05b64a96-d014-5b32-9cb8-a24126644d51
		summarizeBy: none
		sourceColumn: diagnosis

		annotation SummarizationSetBy = Automatic

	column market
		dataType: string
		lineageTag: 00ea8b05-f2bd-5fad-95ff-fafa640c6857
		summarizeBy: none
		sourceColumn: market

		annotation SummarizationSetBy = Automatic

	column cagr_3y_pct
		dataType: double
		lineageTag: cb8d8340-3499-5fd3-bf20-6ccb8e64130f
		summarizeBy: none
		sourceColumn: cagr_3y_pct

		annotation SummarizationSetBy = Automatic

	column actual_deposits
		dataType: double
		lineageTag: 25374152-ad44-51da-a5bd-83bebf64e65f
		summarizeBy: none
		sourceColumn: actual_deposits

		annotation SummarizationSetBy = Automatic

	column predicted_deposits
		dataType: double
		lineageTag: 0e0d3466-0992-5163-a1b5-dfe8acbdf50a
		summarizeBy: none
		sourceColumn: predicted_deposits

		annotation SummarizationSetBy = Automatic

	column catchment_households
		dataType: double
		lineageTag: f06e3f39-4220-523b-9ad2-da4fd76d42fd
		summarizeBy: none
		sourceColumn: catchment_households

		annotation SummarizationSetBy = Automatic

	column booking_concentration
		dataType: boolean
		lineageTag: 22877c41-2d4d-562c-b6a0-9b49ace617af
		summarizeBy: none
		sourceColumn: booking_concentration

		annotation SummarizationSetBy = Automatic

	column catchment_partly_unmeasured
		dataType: boolean
		lineageTag: 4368b34f-d1f0-5409-89ea-ffba753e32f4
		summarizeBy: none
		sourceColumn: catchment_partly_unmeasured

		annotation SummarizationSetBy = Automatic

	measure 'Index (size-adjusted)' =
			AVERAGE ( dim_branch[index_size_adjusted] )
		lineageTag: 76e48862-e16a-52ac-954c-4a6b31bf4db8
		formatString: #,0.000
	measure 'Index (raw)' =
			AVERAGE ( dim_branch[index_raw] )
		lineageTag: b5e41b4c-e4c0-5747-8bce-33b27b7cec95
		formatString: #,0.000
	measure 'Underperforming Branches' =
			CALCULATE ( COUNTROWS ( dim_branch ), dim_branch[index_size_adjusted] < 1 )
		lineageTag: 76638b75-a96e-592e-8b2e-957708d164ce
		formatString: #,0

	partition dim_branch = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataFolder & "\dim_branch.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"uninumbr", type text}, {"cert", type text}, {"institution_name", type text}, {"address", type text}, {"city", type text}, {"state", type text}, {"county_fips", type text}, {"latitude", type number}, {"longitude", type number}, {"tract_geoid", type text}, {"service_type", type text}, {"is_main_office", type text}, {"first_year", Int64.Type}, {"last_year", Int64.Type}, {"drift_kind", type text}, {"position_drift_miles", type number}, {"county_agrees", type logical}, {"validity", type text}, {"is_subject_bank", type logical}, {"index_size_adjusted", type number}, {"index_raw", type number}, {"diagnosis", type text}, {"market", type text}, {"cagr_3y_pct", type number}, {"actual_deposits", type number}, {"predicted_deposits", type number}, {"catchment_households", type number}, {"booking_concentration", type logical}, {"catchment_partly_unmeasured", type logical}})
			in
			    Typed

	annotation PBI_ResultType = Table
