table fact_index_components
	lineageTag: 2ab18a70-4405-5922-b8d1-0ab5f49c4198

	column tract_geoid
		dataType: string
		lineageTag: b2d7387a-ebdf-5afa-bb1c-a3d3699b5f0a
		summarizeBy: none
		sourceColumn: tract_geoid

		annotation SummarizationSetBy = Automatic

	column component
		dataType: string
		lineageTag: 78c5ddd8-c293-5d41-a808-5c26a2573eb0
		summarizeBy: none
		sourceColumn: component

		annotation SummarizationSetBy = Automatic

	column z_score
		dataType: double
		lineageTag: e0456c2f-1d4c-5381-b216-f5ee5468c296
		summarizeBy: none
		sourceColumn: z_score

		annotation SummarizationSetBy = Automatic

	column default_weight
		dataType: double
		lineageTag: 31d8bd8c-4fd6-5739-92f2-78c772c0a633
		summarizeBy: none
		sourceColumn: default_weight

		annotation SummarizationSetBy = Automatic

	measure 'Weight Total' =
			[w Household Growth Value] + [w Median Income Value] + [w Deposit Growth Value] + [w Competitor Saturation Value] + [w Unmet Demand Value]
		lineageTag: f0e087f5-86d8-5b39-b0f6-c32bc856daf3
		formatString: #,0.00
	measure 'Selected Opportunity Score' =
			VAR WeightSum = [Weight Total]
			VAR TotalContribution =
			    SUMX (
			        VALUES ( fact_index_components[component] ),
			        VAR ComponentName = fact_index_components[component]
			        VAR ComponentZ = CALCULATE ( AVERAGE ( fact_index_components[z_score] ) )
			        VAR ComponentWeight =
			            SWITCH (
			                ComponentName,
			                "household_growth", [w Household Growth Value],
			                "median_income", [w Median Income Value],
			                "deposit_market_growth", [w Deposit Growth Value],
			                "competitor_saturation", [w Competitor Saturation Value],
			                "unmet_mortgage_demand", [w Unmet Demand Value],
			                0
			            )
			        RETURN ComponentZ * ComponentWeight
			    )
			RETURN DIVIDE ( TotalContribution, WeightSum )
		lineageTag: 463b28df-e4c3-50a5-b758-67ba2e346858
		formatString: #,0.000

	partition fact_index_components = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataFolder & "\fact_index_components.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"tract_geoid", type text}, {"component", type text}, {"z_score", type number}, {"default_weight", type number}})
			in
			    Typed

	annotation PBI_ResultType = Table
