table recommended_sites
	lineageTag: 95289587-2869-5aeb-90bb-12795f07bac3

	column rule
		dataType: string
		lineageTag: bc3a573a-4740-5b2d-a445-4168738dfd65
		summarizeBy: none
		sourceColumn: rule

		annotation SummarizationSetBy = Automatic

	column tract_geoid
		dataType: string
		lineageTag: db1aba07-b081-53a3-a26b-0c21f90e5204
		summarizeBy: none
		sourceColumn: tract_geoid

		annotation SummarizationSetBy = Automatic

	column county_name
		dataType: string
		lineageTag: 3efb62a6-131f-59ef-8783-6f7ca2b19aad
		summarizeBy: none
		sourceColumn: county_name

		annotation SummarizationSetBy = Automatic

	column cbsa_title
		dataType: string
		lineageTag: 73b6b407-7fe8-5b14-9967-85c5351b379f
		summarizeBy: none
		sourceColumn: cbsa_title

		annotation SummarizationSetBy = Automatic

	column tier
		dataType: string
		lineageTag: c711500b-fd90-5ed6-8bfe-094a5d9ed3fa
		summarizeBy: none
		sourceColumn: tier

		annotation SummarizationSetBy = Automatic

	column households
		dataType: int64
		lineageTag: 459a61f1-1912-5630-8eef-c18b14fa87be
		summarizeBy: none
		sourceColumn: households

		annotation SummarizationSetBy = Automatic

	column lmi_flag
		dataType: boolean
		lineageTag: 08c596ef-10ce-5645-a306-d11c2ae0af21
		summarizeBy: none
		sourceColumn: lmi_flag

		annotation SummarizationSetBy = Automatic

	column opportunity_score
		dataType: double
		lineageTag: dee07e61-463a-5fd3-830c-e9ac7d25c6c6
		summarizeBy: none
		sourceColumn: opportunity_score

		annotation SummarizationSetBy = Automatic

	column unmet_mortgage_demand
		dataType: double
		lineageTag: 82aedb58-3a8c-5fda-8b58-cdbaeace9dfd
		summarizeBy: none
		sourceColumn: unmet_mortgage_demand

		annotation SummarizationSetBy = Automatic

	column growth_is_estimated
		dataType: boolean
		lineageTag: ca492942-fe71-5526-8f4f-84fbccb69ae3
		summarizeBy: none
		sourceColumn: growth_is_estimated

		annotation SummarizationSetBy = Automatic

	partition recommended_sites = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataFolder & "\recommended_sites.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"rule", type text}, {"tract_geoid", type text}, {"county_name", type text}, {"cbsa_title", type text}, {"tier", type text}, {"households", Int64.Type}, {"lmi_flag", type logical}, {"opportunity_score", type number}, {"unmet_mortgage_demand", type number}, {"growth_is_estimated", type logical}})
			in
			    Typed

	annotation PBI_ResultType = Table
