table recommendation_sets
	lineageTag: c02edbeb-1ece-5d92-a326-3cd28a25af75

	column rule
		dataType: string
		lineageTag: 14c0a53c-e0a4-511e-b2fb-1d75bd710971
		summarizeBy: none
		sourceColumn: rule

		annotation SummarizationSetBy = Automatic

	column tract_geoid
		dataType: string
		lineageTag: 386858b3-c681-5129-90e6-de97069b1ea7
		summarizeBy: none
		sourceColumn: tract_geoid

		annotation SummarizationSetBy = Automatic

	column county_name
		dataType: string
		lineageTag: dc0c1e97-4a0c-543f-94a9-9d05f5be1104
		summarizeBy: none
		sourceColumn: county_name

		annotation SummarizationSetBy = Automatic

	column cbsa_title
		dataType: string
		lineageTag: 5b1ecc54-90de-5e77-af6f-ef569098e2b4
		summarizeBy: none
		sourceColumn: cbsa_title

		annotation SummarizationSetBy = Automatic

	column tier
		dataType: string
		lineageTag: 32bea4df-1c92-5b6f-af0d-41db864b897a
		summarizeBy: none
		sourceColumn: tier

		annotation SummarizationSetBy = Automatic

	column households
		dataType: int64
		lineageTag: dfd7ca62-099f-539d-9052-42c8dde106be
		summarizeBy: none
		sourceColumn: households

		annotation SummarizationSetBy = Automatic

	column lmi_flag
		dataType: boolean
		lineageTag: a05a7605-e161-523a-af3b-ef77f10c2da3
		summarizeBy: none
		sourceColumn: lmi_flag

		annotation SummarizationSetBy = Automatic

	column opportunity_score
		dataType: double
		lineageTag: 70d083fb-5fe5-5b1a-8ee0-90c984f971a3
		summarizeBy: none
		sourceColumn: opportunity_score

		annotation SummarizationSetBy = Automatic

	column unmet_mortgage_demand
		dataType: double
		lineageTag: df3d237b-8c81-5265-be7c-94355a07390b
		summarizeBy: none
		sourceColumn: unmet_mortgage_demand

		annotation SummarizationSetBy = Automatic

	column growth_is_estimated
		dataType: boolean
		lineageTag: 4a80da5b-45c8-5aee-9985-24be08cbf48b
		summarizeBy: none
		sourceColumn: growth_is_estimated

		annotation SummarizationSetBy = Automatic

	column centroid_lat
		dataType: double
		dataCategory: Latitude
		lineageTag: 0fefac74-3844-50ef-b53f-2694ae32760f
		summarizeBy: none
		sourceColumn: centroid_lat

		annotation SummarizationSetBy = Automatic

	column centroid_lon
		dataType: double
		dataCategory: Longitude
		lineageTag: 14ac5c3d-e3a5-55d0-93da-ca88d12ca4f3
		summarizeBy: none
		sourceColumn: centroid_lon

		annotation SummarizationSetBy = Automatic

	column county_fips
		dataType: string
		lineageTag: 7ba1fe76-47bb-54fb-8a45-2c77aa9ea737
		summarizeBy: none
		sourceColumn: county_fips

		annotation SummarizationSetBy = Automatic

	partition recommendation_sets = m
		mode: import
		source =
			let
			    Source = Csv.Document(File.Contents(DataFolder & "\recommendation_sets.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
			    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
			    Typed = Table.TransformColumnTypes(Promoted, {{"rule", type text}, {"tract_geoid", type text}, {"county_name", type text}, {"cbsa_title", type text}, {"tier", type text}, {"households", Int64.Type}, {"lmi_flag", type logical}, {"opportunity_score", type number}, {"unmet_mortgage_demand", type number}, {"growth_is_estimated", type logical}, {"centroid_lat", type number}, {"centroid_lon", type number}, {"county_fips", type text}})
			in
			    Typed

	annotation PBI_ResultType = Table
